import { Fira_Code } from 'next/font/google';
import NextTopLoader from 'nextjs-toploader';
import './globals.css';

const firaCode = Fira_Code({ subsets: ['latin'] });

export const metadata = {
	title: 'Naufal Firman | Portofolio Web',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<head>
				<link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-touch-icon.png" />
				<link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png" />
				<link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png" />
				<link rel="manifest" href="/favicon/site.webmanifest" />
			</head>
			<body className={`${firaCode.className} selection:bg-primary selection:text-secondary`}>
				<NextTopLoader showSpinner={false} color="#C778DD" />
				{children}
			</body>
		</html>
	);
}
